### ISSUE TITLE
dbus.exceptions.DBusException: org.ladish.Error.UnknownMethod: Method "GetAll2" with signature "" on interface "org.ladish.AppSupervisor" doesn't exist

### ISSUE THREAD

**Issue by nilehmann** [falkTX/Cadence#123]
I get the following error when loading an studio in claudia. I have ladish and python-dbus installed.

```
Traceback (most recent call last):
  File "/usr/share/cadence/src/claudia.py", line 2261, in slot_DBusStudioAppearedCallback
    self.studioLoaded()
  File "/usr/share/cadence/src/claudia.py", line 1421, in studioLoaded
    self.init_studio()
  File "/usr/share/cadence/src/claudia.py", line 1050, in init_studio
    self.init_apps().
  File "/usr/share/cadence/src/claudia.py", line 1056, in init_apps
    graph_version, app_list = studio_iface.GetAll2()
  File "/usr/lib/python3.5/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.ladish.Error.UnknownMethod: Method "GetAll2" with signature "" on interface "org.ladish.AppSupervisor" doesn't exist
```

**Comment by falkTX** [comment]
what ladish version are you using? 0.3?
that would be really old...

**Comment by nilehmann** [comment]
I installed both [cadence](https://aur.archlinux.org/packages/cadence/) and [cadence-git](https://aur.archlinux.org/packages/cadence-git/) from the AUR, trying with [ladish](https://aur.archlinux.org/packages/ladish/) and [ladish-git](https://aur.archlinux.org/packages/ladish-git/) obtaining the same result.

**Comment by falkTX** [comment]
both are using 0.3.x for some reason, which is very old.
1.0 has been out since a few years.

ladish is more or less dead anyway...
