### ISSUE TITLE
Cadence fails to start

### ISSUE THREAD

**Issue by slackhead** [falkTX/Cadence#138]
Output:

> dbus-launch cadence
Using Tray Engine 'Qt'
Traceback (most recent call last):
  File "/usr/share/cadence/src/cadence.py", line 2319, in <module>
    gui = CadenceMainW()
  File "/usr/share/cadence/src/cadence.py", line 751, in __init__
    self.loadSettings(True)
  File "/usr/share/cadence/src/cadence.py", line 2257, in loadSettings
    self.restoreGeometry(self.settings.value("Geometry", ""))
TypeError: QWidget.restoreGeometry(QByteArray): argument 1 has unexpected type 'QVariant'

**Comment by slackhead** [comment]
I was informed on the linuxaudio forum that cadence needs python3. Is there any way at all of getting it working with python2?

**Comment by falkTX** [comment]
no way. python2 is obsolete for a few years now.
if something needs to change in cadence is moving from qt4 to qt5.
