### ISSUE TITLE
cant set jack settings

### ISSUE THREAD

**Issue by euri10** [falkTX/Cadence#144]
it seems like this is the same issue as the one here from 2y ago https://github.com/falkTX/Cadence/issues/70
Using the compiled build I got this
```
  inflating: /tmp/cadence-jacksettings/libffi.so.5
  inflating: /tmp/cadence-jacksettings/cadence-jacksettings
Traceback (most recent call last):
  File "/usr/share/cx-freeze-common/initscripts/Console3.py", line 27, in <module>
  File "./build/opt/cadence/share/cadence/src/jacksettings.py", line 917, in <module>
  File "./build/opt/cadence/share/cadence/src/jacksettings.py", line 231, in __init__
  File "./build/opt/cadence/share/cadence/src/jacksettings.py", line 369, in loadServerSettings
TypeError: 'NoneType' object is not subscriptable
```

**Comment by falkTX** [comment]
Please build it yourself if possible.

**Comment by euri10** [comment]
building it from source I got all grey
```➜  Cadence git:(master) cadence
Using Tray Engine 'Qt'
No systemtrayicon available
```
![Image](http://imgur.com/qpMSyT9)

I can run cadence-jacksettings though
