### ISSUE TITLE
cadence-session-start problem; DBus Failed to open server

### ISSUE THREAD

**Issue by milkmiruku** [falkTX/Cadence#147]
`cadence-session-start --system-start` returns

> Traceback (most recent call last):
>   File "/usr/share/cadence/src/cadence_session_start.py", line 234, in <module>
>     sys.exit(startSession(True, arg == "--system-start-desktop"))
>   File "/usr/share/cadence/src/cadence_session_start.py", line 116, in startSession
>     startJack()
>   File "/usr/share/cadence/src/cadence_session_start.py", line 147, in startJack
>     DBus.jack.StartServer()
>   File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
>     **keywords)
>   File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
>     message, timeout)
> dbus.exceptions.DBusException: org.jackaudio.Error.Generic: Failed to open server

This happens whether `jack_control start` is run before or not. Afterward jack is stopped.

**Comment by milkmiruku** [comment]
This was resolved after running `cadence-session-start --reset`.
