### ISSUE TITLE
Fails on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [falkTX/Cadence#194]
Hi falkTX,

I've created a draft port https://reviews.freebsd.org/D13800, but it fails:
```
$ cadence
Using Tray Engine 'Qt'
Traceback (most recent call last):
  File "/usr/local/share/cadence/src/cadence.py", line 2320, in <module>
    gui = CadenceMainW()
  File "/usr/local/share/cadence/src/cadence.py", line 752, in __init__
    self.loadSettings(True)
  File "/usr/local/share/cadence/src/cadence.py", line 2258, in loadSettings
    self.restoreGeometry(self.settings.value("Geometry", ""))
TypeError: restoreGeometry(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'QVariant'
```

Are you able to tell what's wrong?

Thanks!
Yuri

**Comment by falkTX** [comment]
Yes, a breaking change in PyQt.
Cadence will soon be converted to Qt5, so this and a lot of other stuff will be handled.
