### ISSUE TITLE
Cadence broken

### ISSUE THREAD

**Issue by erwan35** [falkTX/Cadence#206]
Hello,

I have updated cadence from 2:0.8.1+git20170711 to 2:0.9.0~git20180318v5 and it's broken for me.

`Using Tray Engine 'Qt'
Traceback (most recent call last):
  File "/usr/share/cadence/src/cadence.py", line 42, in <module>
    from shared_canvasjack import *
  File "/usr/share/cadence/src/shared_canvasjack.py", line 35, in <module>
    import jacksettings
  File "/usr/share/cadence/src/jacksettings.py", line 23, in <module>
    from PyQt4.QtCore import pyqtSlot, Qt, QSettings, QTimer, SIGNAL, SLOT
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class`

I'm running Ubuntu Xenial.

Cheers
Erwan

**Comment by falkTX** [comment]
you did a partial upgrade, make sure to update everything.

**Comment by erwan35** [comment]
Oups... I had to install cadence-tools :)
