### ISSUE TITLE
Catia and Cadence won't start

### ISSUE THREAD

**Issue by bashman** [falkTX/Cadence#210]
`bashman@lucy:~$ cadence
Using Tray Engine 'Qt'
Traceback (most recent call last):
  File "/usr/share/cadence/src/cadence.py", line 42, in <module>
    from shared_canvasjack import *
  File "/usr/share/cadence/src/shared_canvasjack.py", line 35, in <module>
    import jacksettings
  File "/usr/share/cadence/src/jacksettings.py", line 22, in <module>
    from PyQt4.QtCore import pyqtSlot, Qt, QSettings, QTimer, SIGNAL, SLOT
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
bashman@lucy:~$
`
All is working fine. 
Linux 64. Gnome ubuntu 16.04

**Comment by falkTX** [comment]
Please update all packages, you have done a partial upgrade.
So parts of cadence are qt4, and some are qt5. This cannot work.
Update everything (eg, `sudo apt-get dist-upgrade`) and it will work fine again.
