### ISSUE TITLE
Unable to Launch Claudia

### ISSUE THREAD

**Issue by LividJava** [falkTX/Cadence#319]
Hey there, Just installed JACK using cadence-git from the AUR
using Manjaro... but i am unable to launch Claudia for whatever reason, attempting to launch from the terminal presents with the following.

```
Using Tray Engine 'Qt'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.ladish': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/cadence/src/claudia.py", line 2753, in <module>
    gDBus.ladish_control = gDBus.bus.get_object("org.ladish", "/org/ladish/Control")
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.ladish was not provided by any .service files
```

Not quite sure what I'm missing here?? i'm trying to get a JACK setup for streaming and such

**Comment by falkTX** [comment]
Missing ladish, as claudia is a ladish frontend.

ladish project has been in limbo for a while, so might just have been removed from archlinux altogether.

**Comment by simotek** [comment]
> Missing ladish, as claudia is a ladish frontend.
> 
> ladish project has been in limbo for a while, so might just have been removed from archlinux altogether.

On openSUSE we build ladish without the UI because it uses gtk libs that no longer exist, doing so works fine especially given were using claudia as a frontend anyway.
