### ISSUE TITLE
Unable to launch Claudia due to unexpected type 'float' arguments (patch)

### ISSUE THREAD

**Issue by themanyone** [falkTX/Cadence#327]
I was having trouble launching Claudia from the Fedora, disro package:
 Cadence-1.0.0-0.17.20210316gitc146ff9.fc35.x86_64

So I hacked around the errors with the following
[canvaspreviewframe.py.patch.txt](https://github.com/falkTX/Cadence/files/6978987/canvaspreviewframe.py.patch.txt)

```
$ claudia
Using Tray Engine 'Qt'
Traceback (most recent call last):
  File "/usr/share/cadence/src/claudia.py", line 2768, in <module>
    gui = ClaudiaMainW()
  File "/usr/share/cadence/src/claudia.py", line 786, in __init__
    self.ui.miniCanvasPreview.init(self.scene, DEFAULT_CANVAS_WIDTH, DEFAULT_CANVAS_HEIGHT)
  File "/usr/share/cadence/src/canvaspreviewframe.py", line 76, in init
    self.setMinimumSize(self.fFakeWidth+padding,   self.fFakeHeight+padding)
TypeError: arguments did not match any overloaded call:
  setMinimumSize(self, int, int): argument 1 has unexpected type 'float'
  setMinimumSize(self, QSize): argument 1 has unexpected type 'float'

```

**Comment by Yarkhan** [comment]
Thank you. The patch works for me.

**Comment by themanyone** [comment]
Closing due to time expired
