### ISSUE TITLE
TypeError: setEnabled(self, bool): argument 1 has unexpected type 'NoneType'

### ISSUE THREAD

**Issue by jeberger** [falkTX/Cadence#334]
When attempting to run Catia on Pipewire instead of Jack, Catia crashes with:

```
Traceback (most recent call last):
  File "/usr/share/cadence/src/catia.py", line 1428, in <module>
    gui = CatiaMainW()
  File "/usr/share/cadence/src/catia.py", line 169, in __init__
    if self.jackStarted():
  File "/usr/share/cadence/src/catia.py", line 919, in jackStarted
    self.menuJackServer(True)
  File "/usr/share/cadence/src/catia.py", line 998, in menuJackServer
    self.menuA2JBridge(False)
  File "/usr/share/cadence/src/catia.py", line 1012, in menuA2JBridge
    self.ui.act_tools_a2j_export_hw.setEnabled(gDBus.a2j and not gDBus.a2j.is_started())
TypeError: setEnabled(self, bool): argument 1 has unexpected type 'NoneType'
```

This can be fixed by replacing the offending line with:

```
self.ui.act_tools_a2j_export_hw.setEnabled(bool(gDBus.a2j) and not gDBus.a2j.is_started())
```

**Comment by livmackintosh** [comment]
I can confirm that I also have the same problem and that your solution fixes it.

Olivia

**Comment by nyanpasu64** [comment]
I also get this error on an Arch Linux machine with PipeWire installed but disabled in `systemctl --user`, and the real jack2 running from qjackctl.
