### ISSUE TITLE
Claudia won't start - complains DBUS is missing

### ISSUE THREAD

**Issue by cleinias** [falkTX/Cadence#340]
Launching Claudia from either the Cadence panel or from terminal produces an error message 

"DBus is not available, Claudia cannot start without it!"

But DBus is installed, as far as I can tell:
````
stefano@gorgias  $ pacman -Qs dbus
local/bluez-qt 5.90.0-1 (kf5)
    Qt wrapper for Bluez 5 DBus API
local/dbus 1.12.20-1
    Freedesktop.org message bus system
local/dbus-c++ 0.9.0-9
    A C++ API for D-BUS
local/dbus-glib 0.112-2
    GLib bindings for DBUS
local/jack2-dbus 1.9.19-2
    The JACK low-latency audio server (dbus integration)
local/kdbusaddons 5.90.0-1 (kf5)
    Addons to QtDBus
local/lib32-dbus 1.12.20-1
    Freedesktop.org message bus system (32-bit)
local/lib32-libdbusmenu-glib 16.04.0-4
    Library for passing menus over DBus (32-bit)
local/lib32-libdbusmenu-gtk2 16.04.0-4
    Library for passing menus over DBus (32-bit) (GTK+ 2 library)
local/libcloudproviders 0.3.1-2
    DBus API that allows cloud storage sync clients to expose their services
local/libdbusmenu-glib 16.04.0-4
    Library for passing menus over DBus
local/libdbusmenu-gtk2 16.04.0-4
    Library for passing menus over DBus (GTK+ 2 library)
local/libdbusmenu-gtk3 16.04.0-4
    Library for passing menus over DBus (GTK+ 3 library)
local/libdbusmenu-qt4 0.9.3+16.04.20160218-2
    A library that provides a Qt4 implementation of the DBusMenu spec
local/libdbusmenu-qt5 0.9.3+16.04.20160218-6
    A library that provides a Qt implementation of the DBusMenu spec
local/libmm-qt 1.0.1-2
    Qt-only wrapper for ModemManager DBus API
local/libnm-qt4 0.9.8.4-1
    Qt4-only wrapper for NetworkManager DBus API
local/modemmanager-qt 5.90.0-1 (kf5)
    Qt wrapper for ModemManager DBus API
local/python-dbus 1.2.16-3
    Python bindings for DBUS
local/python-dbus-common 1.2.16-3
    Common dbus-python files shared between python-dbus and python2-dbus
local/python-jeepney 0.7.1-3
    Low-level, pure Python DBus protocol wrapper
local/python2-dbus 1.2.16-3
    Python2 bindings for DBUS
local/xdg-dbus-proxy 0.1.2-3
````

What else am I missing?

**Comment by ohquait** [comment]
better will be you post the error-outputs from terminal here, like this:
```
[....@localhost ~]$ su -c claudia
Password: 
Using Tray Engine 'Qt'
QStandardPaths: runtime directory '/var/run/user/500' is not owned by UID 0, but a directory permissions 0700 owned by UID 500 GID 0
Traceback (most recent call last):
  File "/usr/share/cadence/src/claudia.py", line 2752, in <module>
    gDBus.bus  = dbus.SessionBus(mainloop=gDBus.loop)
  File "/usr/lib/python3.6/site-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3.6/site-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[....@localhost ~]$ 
```

**Comment by ohquait** [comment]
with a fresh build of ladish, claudia works now
