### ISSUE TITLE
setMinimumSize : unexpected type 'float'

### ISSUE THREAD

**Issue by AnasGhrab** [falkTX/Cadence#347]
Hi. With the last versions of Claudia and Ubuntu 22 TLS, I get this error when lauching Claudia :

```
anas@Zeus:~$ claudia
Using Tray Engine 'Qt'
Traceback (most recent call last):
  File "/usr/share/cadence/src/claudia.py", line 2768, in <module>
    gui = ClaudiaMainW()
  File "/usr/share/cadence/src/claudia.py", line 786, in __init__
    self.ui.miniCanvasPreview.init(self.scene, DEFAULT_CANVAS_WIDTH, DEFAULT_CANVAS_HEIGHT)
  File "/usr/share/cadence/src/canvaspreviewframe.py", line 76, in init
    self.setMinimumSize(self.fFakeWidth+padding,   self.fFakeHeight+padding)
TypeError: arguments did not match any overloaded call:
  setMinimumSize(self, int, int): argument 1 has unexpected type 'float'
  setMinimumSize(self, QSize): argument 1 has unexpected type 'float'
```

**Comment by WiredG1** [comment]
Having the same issue

**Comment by mvdev0** [comment]
Me too.. this is the terminal output

`~$ claudia
Using Tray Engine 'Qt'
Traceback (most recent call last):
  File "/usr/share/cadence/src/claudia.py", line 2768, in <module>
    gui = ClaudiaMainW()
  File "/usr/share/cadence/src/claudia.py", line 786, in __init__
    self.ui.miniCanvasPreview.init(self.scene, DEFAULT_CANVAS_WIDTH, DEFAULT_CANVAS_HEIGHT)
  File "/usr/share/cadence/src/canvaspreviewframe.py", line 76, in init
    self.setMinimumSize(self.fFakeWidth+padding,   self.fFakeHeight+padding)
TypeError: arguments did not match any overloaded call:
  setMinimumSize(self, int, int): argument 1 has unexpected type 'float'
  setMinimumSize(self, QSize): argument 1 has unexpected type 'float'`

**Comment by mvdev0** [comment]
Thanks falkTX!

**Comment by loquesangra** [comment]
Reproduced on latest Obarun (Arch-Based) Linux from cadence-claudia AUR package, with freshly-built dependencies.

**Comment by loquesangra** [comment]
However, updating the package to 0.9.2 makes it work!

**Comment by eyagass99** [comment]
> However, updating the package to 0.9.2 makes it work!

how can i update it !
