### ISSUE TITLE
Cadence: abrupt JACK device removal issue

### ISSUE THREAD

**Issue by danboid** [falkTX/Cadence#39]
(copy/pasted from original LM forum posting)

THE PROBLEM

I am happily running Cadence on an external (in this case USB) sound device then someone (in this case evil danboid) removes said device without adjusting Cadence or thinking to switch device properly first.

RESULT

Cadence stops responding and doesn't let you switch to a new device like the onboard audio. Trying to start Cadence from the command line in this state says:

dan@dan-SR700:~$ cadence
Using Tray Engine 'Qt'
ERROR:dbus.proxies:Introspect error on :1.95:/org/jackaudio/Controller: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/share/cadence/src/cadence.py", line 2296, in <module>
    gui = CadenceMainW()
  File "/usr/share/cadence/src/cadence.py", line 1189, in **init**
    self.DBusReconnect()
  File "/usr/share/cadence/src/cadence.py", line 1211, in DBusReconnect
    if gDBus.jack.IsStarted():
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in **call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

CURRENT SOLUTION

Kill Cadence, run 'cadence-session-start -s', reopen Cadence and all is well

DESIRED FIX

It would be nice if Cadence could detect when this has happened and restart the cadence session daemon automatically.

**Comment by naught101** [comment]
It might also be nice to have the option to automatically switch-master back to the internal sound card when a USB interface is removed.
